USE [master]
GO

/****** Object:  Database [PruebaTecnicaFundamicro]    Script Date: 7/9/2026 8:31:36 AM ******/
CREATE DATABASE [PruebaTecnicaFundamicro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaTecnicaFudamicro', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PruebaTecnicaFudamicro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaTecnicaFudamicro_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PruebaTecnicaFudamicro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaTecnicaFundamicro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET ARITHABORT OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET  MULTI_USER 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET QUERY_STORE = ON
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PruebaTecnicaFundamicro] SET  READ_WRITE 
GO


